### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by ghost** [pavelk2/social-feed#191]
At the moment you can search for feeds only in specific account, it is possible (as the FB site) always try via hashtag but all over facebook, a global search?

**Comment by HartLarsson** [comment]
searching by #hasthtags i think is not possible by API. 
https://developers.facebook.com/docs/graph-api/using-graph-api/v1.0#searchtypes

i've seen people find a workaround time ago using %23 instead of # but i'm not sure is working today
you can try yourself using this syntax:

https://graph.facebook.com/search?q=%23YOU-HASH-VALUE&limit=10000&access_token=YOUR-ACCESS-TOKEN

I think is deprecated and not works anymore.

**Comment by ghost** [comment]
Perfect! Thanks a lot for the answer.
