### ISSUE TITLE
Twitter 1.1 API

### ISSUE THREAD

**Issue by ghost** [pavelk2/social-feed#21]
The method used to get the twitter feeds will be deprechated in the 1.1 API (not fully but will require authorization).

https://dev.twitter.com/docs/api/1/get/statuses/user_timeline

Any idea to replace this method?

**Comment by pavelk2** [comment]
Hello, 
I think that you can use one of three methods, described in https://dev.twitter.com/docs/working-with-timelines

**Comment by minicstudio** [comment]
Do you intend to upgrade the social-feed?

**Comment by pavelk2** [comment]
I do intend to upgrade the social-feed, but not in the next few weeks. I would estimate the next upgrade on the end of the august, beginning of september.

**Comment by pavelk2** [comment]
The idea of Social-feed is to have a very light plugin which has only front-end. In order to support the Twitter 1.1 Api - the tweet fetching system should be implemented on the server side. I am not sure that i will implement it here - as you can easily do it with one of available open-source plugins for server-side frameworks.
