### ISSUE TITLE
Problem with Twitter dates in IE11 and Edge

### ISSUE THREAD

**Issue by rgpgithub** [pavelk2/social-feed#244]
The Twitter dates just say "a few seconds ago" when returned in IE and Edge.  They are perfectly ok when returned in Firefox, Chrome, Opera and Safari.  See attached screen shots from IE and Firefox.

![ie-screen-shot](https://cloud.githubusercontent.com/assets/25645208/22752176/7af4a65c-ee2f-11e6-821c-979b0e198203.jpg)

![firefox-screen-shot](https://cloud.githubusercontent.com/assets/25645208/22752188/83ed6eb0-ee2f-11e6-826f-eefb604ad908.jpg)

**Comment by HartLarsson** [comment]
![image](https://cloud.githubusercontent.com/assets/16102074/22779279/5c01107e-eeba-11e6-85fd-c9edcab9a4b4.png)

i still using edge without any problem for facebook, g+ and so on except twitter as shown in the pic accessing the page https://pavelk2.github.io/social-feed-example/

Probably twitter date must be reviewed in the code

**Comment by HartLarsson** [comment]
anyway i suggest you to download and create your API id/keys and not use the demo value because could be overquota or not valid for your account

**Comment by rgpgithub** [comment]
Thank you for your prompt reply.  I was only using the demo keys to evaluate the code for potential use in a site I am building and will create my own API keys if I decide to use socialfeed.js.  Not sure what you mean by "Probably twitter date must be reviewed in the code"?  Why does it work in all other browsers other than IE11 and Edge?

**Comment by HartLarsson** [comment]
i've took a look to the js code and the latest introduction could be a problem here:
![image](https://cloud.githubusercontent.com/assets/16102074/22780390/d8f78258-eebe-11e6-8efa-8165fa3266f8.png)

I need to debug better this function because my FORKED version that not use this js version works perfectly on IE, opera, chrome, safari etc.. etc..

Have you tried to download the demo and modify the language ID to match your local version?
![image](https://cloud.githubusercontent.com/assets/16102074/22780591/8712bab0-eebf-11e6-82df-63f6cc39b444.png)

**Comment by HartLarsson** [comment]
if you want to try my forked version with a new rendering engine (all post from all socials are ordered by data) : https://github.com/HartLarsson/social-feed/blob/gh-pages/js/jquery.socialfeed-render.js

**Comment by HartLarsson** [comment]
after a check I discovered that the demo use the **old version of the js code** that is affected by IE/edge date bug.
Please download the latest version that works ok

**Comment by rgpgithub** [comment]
Downloaded the latest version and all works perfectly now in IE and Edge.  Thanks for you help.
