### ISSUE TITLE
Instagram not working + date_locale don't display the right locale

### ISSUE THREAD

**Issue by wedot** [pavelk2/social-feed#325]
Hi there

Will there be a fix for the Instagram feed? 

In my jquery funktion i use the date_locale: "en" but it will be always be displayed in french.
What do i wrong?

**Comment by martijngastkemper** [comment]
For updates on Instagram look for updates in the issues about that problem.

The locales aren't loaded by default. You can load the French locale by adding this tag: ``<script src="bower_components/moment/locale/fr.js"></script>``

If you want to load all locale load ``moment-with-locales.min.js`` instead of ``moment.min.js``.
