### ISSUE TITLE
Facebook problem - how to solve this?

### ISSUE THREAD

**Issue by htrxuan** [pavelk2/social-feed#340]
"message": "(#10) To use 'Page Public Content Access', your use of this endpoint must be reviewed and approved by Facebook. To submit this 'Page Public Content Access' feature for review please read our documentation on reviewable features: https://developers.facebook.com/docs/apps/review."

Anyone solve this error? Help me. I try to submit review but cant get facebook feed

**Comment by vushe** [comment]
Welcome:
https://github.com/pavelk2/social-feed/issues/330

**Comment by HartLarsson** [comment]
is a facebook problem, there is nothing we can do on the js script.

**Comment by htrxuan** [comment]
yes, I had solved this

**Comment by MladenJanjetovic** [comment]
> yes, I had solved this

How?

**Comment by htrxuan** [comment]
Hi,
All FB apps must submit to review

![1st app app review facebook for developers](https://user-images.githubusercontent.com/795384/47561438-78f39400-d945-11e8-9f22-1781a069f3ac.png)

**Comment by MladenJanjetovic** [comment]
@htrxuan I did, like several times. And I am getting declined all the time. The last time they said they couldn't find a FB login button on the website (wtf?!). It's my FB app, and I am the admin of that FB Page. And just want to get the public posts. 

Now my client has to open the Facebook Business account in order to ask them a question. Because their responses are so generic and seems like they didn't look at the video and my description at all.
This is insane.

![image](https://user-images.githubusercontent.com/4288643/47562920-6c107980-d920-11e8-9953-190958fbc980.png)
