### ISSUE TITLE
RSS Feeds Not working Due to Retirement of query.yahooapis.com

### ISSUE THREAD

**Issue by rgpgithub** [pavelk2/social-feed#346]
RSS feeds return an error due to the retirement of the YahooAPI's as per the following

https://stackoverflow.com/questions/54046823/yql-query-service-replacement-now-that-yahoo-shut-it-down

Do you have an alternative RSS feed method

**Comment by rgpgithub** [comment]
@HartLarsson @martijngastkemper it seems you guys do a lot of the maintenance on the Social Feed JS, do you have any thoughts on this RSS issue and a potential alternative to the Yahoo YQL service.  Thanks.

**Comment by HartLarsson** [comment]
the proxy solution is doable but that means you need a php file for proxy service. This time is not depending to other services.
The same could be done to pervent to make API key and secret pass public creating a php file that retriew info from facebook ad other socials that need api keys.

The problem is i've no time to implement that solution :(
