### ISSUE TITLE
Realtime update feature for latest updates from the pages/feed

### ISSUE THREAD

**Issue by sahanDissanayake** [pavelk2/social-feed#37]
Would love to have a feature where you could have realtime updates from facebook twitter mainly.

Any information you may have on this would be much appreciated.

Cheers.

**Comment by pavelk2** [comment]
In order to get updates in realtime you need to have your server side, which a social network (facebook/twitter) will call everytime a new update appears. Then you need to have a web-socket connection implemented by yourself, or using third party services, like firebase.com, goinstant.com, parse.com etc.

**Comment by pavelk2** [comment]
I think that real time update is not a part of social-feed plugin and should be implemented additionally. I close this issue because of that.
