### ISSUE TITLE
doesn't work after upgrade

### ISSUE THREAD

**Issue by manlioma** [pavelk2/social-feed#66]
hi, do you know where is the problem?

please help me!

http://www.bombadischi.it/

**Comment by pavelk2** [comment]
I did not get - what specifically does not work? I see that you have a timeline from social-networks. Do you want to have something different? Please provide some details.

**Comment by manlioma** [comment]
Hello Pavel, sorry for delay, now I have a timeline from different plugin, beacause this one doesn't works.. otherwise, it is installed now, I try do get you another page with only this plugin.

Try here

http://www.bombadischi.it/social-feed/

I see that works, only limit content feed at 2, up to 2 it doesn't works.. any ideas ?

**Comment by pavelk2** [comment]
So as I see the problem is not with Social-feed, but with the javascript in general. Please see the errors you have in your console:
https://www.dropbox.com/s/qczo2bi1whslqgu/Screenshot%202015-02-24%2014.30.11.png?dl=0
So even when you try to run $('div') - it does not work. As soon as you have it working I believe the social-feed will work also.

**Comment by manlioma** [comment]
Hi there, thank you very much for your answer..
I didn't see any error in my console.. see here

https://www.dropbox.com/s/ri9nxmu02fysclc/console-log.png?dl=0

How I can resolve about you ? because, if i set limit at 2 post..it is
working well!
thank you

**Comment by pavelk2** [comment]
@manlioma do you still experience the issue?
