### ISSUE TITLE
jQuery Isotope issue

### ISSUE THREAD

**Issue by ChristopherDosin** [pavelk2/social-feed#94]
If i try to load the social feed inside of jQuery Isotope elements Isotopes seems not to be working.
Can you confirm this bug ?

If so - is there any hotfix to load the social feed inside Isotope ?

**Comment by pavelk2** [comment]
Dear @hostianer,
I did not try to load socialfeed with Isotope (i believe you are talking about this http://isotope.metafizzy.co/).
Could you please share a piece of code you use for the integration - so i can check it out, without starting from scratch.

I believe that if there is a problem - it can be caused by the fact that Isotope most likely expects to have a static container with elements inside, while in social-feed the elements are loaded and dynamically added. May be if you initiate Isotope after all the posts are loaded and rendered by socialfeed - it will work.

**Comment by ChristopherDosin** [comment]
Hi @pavelk2 

thanks for your reply buddy :+1: 

yep this is what i am talking about.

I already figured out that this is because the ajax loading.

Heres a link:
http://46.101.146.17/
And here is the social JS file: http://46.101.146.17/assets/js/custom.js

I wrote this little code to the callback function but it seems that this function is not loading:

```
 $("#social-twitter-stream").each(function() {
                var $social = $(this);
                $social.social($social.data());
            });
```

If i execute the script manually in the dev tools console its working.

**Comment by pavelk2** [comment]
Ok,
You might try to use the callback function implemented here
https://github.com/pavelk2/social-feed/pull/80
So after all the posts are collected and rendered - you use the isotope.
Let me know how it goes.

**Comment by ChristopherDosin** [comment]
I already used you callback function

```
// When all the posts are collected and displayed - this function is evoked
        callback: function(){

            $("#social-twitter-stream").each(function() {
                var $social = $(this);
                $social.social($social.data());
            });

            console.log('all posts are collected');
        }
```

unfortunately i dont know much about javascript so i dont know which code i have to use fom #80
